name: Continuous Deployment Workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:
  deploy_staging:
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm ci

      - name: Build app
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./build
